knp_snappy:
    pdf:
        enabled:    true
        binary:     '%kernel.project_dir%/assets/natives/usr/bin/wkhtmltopdf'
        options:  []
    image:
        enabled:    true
        binary: '%kernel.project_dir%/../wkhtmltopdf/bin/wkhtmltopdf.exe'
        options: []
