vich_uploader:
    db_driver: orm
    mappings:
        correction:
            uri_prefix: /images/corrections
            upload_destination: '%kernel.project_dir%/public_html/images/corrections/'

            inject_on_load: false
            delete_on_update: true
            delete_on_remove: true
